### ISSUE TITLE
Small amounts of spacing with each escape code ruins monospacing

### ISSUE THREAD

**Issue by AaronKutch** [TobiasFaller/vscode-vt100-syntax-highlight#28] opened 2022-06-08 04:53 UTC
I've been using this for visualizing error tests side by side, thought that something must be wrong with my code but discovered that something about spacing is not being upheld, even when using a monospace font. Here is in the console:
![image](https://user-images.githubusercontent.com/32419308/172534010-ce882f0e-bfbd-44e1-a9ce-b1bd18519c50.png)
and in the extension's preview:
![image](https://user-images.githubusercontent.com/32419308/172533926-dd0499e1-a8b5-48e9-b2ac-98b22b55ddec.png)
It appears monospace at first but different amounts of punctuation and spaces slowly makes columns out of sync.

**Comment by AaronKutch** [comment] 2022-06-08 04:59
It seems the control characters add a small amount of space
![image](https://user-images.githubusercontent.com/32419308/172535147-07d6b2f4-71c5-49a0-a264-c63bab246b9b.png)
![image](https://user-images.githubusercontent.com/32419308/172535180-cf24cfd4-cf9e-4884-b134-90c24e26eae6.png)

**Comment by TobiasFaller** [comment] 2023-01-06 19:54
Fixed with version 1.0.2: Default configuration now only adds vertical whitespace for groups instead of vertical and horizontal space.

**Closed by TobiasFaller** 2023-01-06 19:54 UTC

**Comment by AaronKutch** [comment] 2023-01-06 20:13
thank you!

**Comment by TobiasFaller** [comment] 2023-01-06 20:18
@AaronKutch I hope that the issue is now fixed for you too. Should it still persist then feel free to open another issue, provide me a failing example and I'll investigate further.

**Comment by AaronKutch** [comment] 2023-01-06 20:21
It looks fixed
